name: detekt Auto Testing

on:
  pull_request:
    branches: [ "release/*", "hotfix/*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: run assembleRelease
        run: ./gradlew assembleRelease
