name: release build Testing

on:
  pull_request:
    branches: [ "main", "release/**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '17'
          cache: 'gradle'
          
      - name: generate local.properties
        env:
          DHC_SERVER_BASE_URL: ${{ secrets.DHC_SERVER_BASE_URL }}
        run:
          echo DHC_SERVER_BASE_URL=$DHC_SERVER_BASE_URL > local.properties

      - name: Putting Google Json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}
        run: |
          mkdir -p /home/runner/work/DHC-Android/DHC-Android/app
          echo "$GOOGLE_SERVICES_JSON" > /home/runner/work/DHC-Android/DHC-Android/app/google-services.json

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: run assembleRelease
        run: ./gradlew assembleRelease
